---

- name: Set up partition
  ansible.builtin.include_role:
    name: khaledk2.lvm_partition
  vars:
    lvm_lvname: docker-volume
    lvm_lvmount: /var/lib/docker
    lvm_lvsize: "{{ docker_volumesize }}"
    lvm_lvfilesystem: "{{ docker_lvfilesystem }}"
    lvm_lvopts: "{{ docker_lvopts | default(None) }}"
  when: docker_use_custom_storage
