---
- name: Converge
  hosts: all
  roles:
    - role: ome.docker
      docker_additional_options:
        hosts:
          - tcp://127.0.0.1:4243
          - unix:///var/run/docker.sock
    name: ome.lvm_partition
      vars:
        lvm_vgname: "{{ docker_vgname }}"
        lvm_lvname: docker-volume
        lvm_lvmount: /var/lib/docker
        lvm_lvsize: "{{ docker_volumesize }}"
        lvm_lvfilesystem: "{{ docker_lvfilesystem }}"
        lvm_lvopts: "{{ docker_lvopts | default(None) }}"
      when: docker_use_custom_storage


  tasks:
    - name: create unprivileged user
      become: true
      user:
        name: test
        state: present
